#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fm-mgr
Version  : 80afa6133f70b6e3e25befe3f993c2a1bf1cb0bf
Release  : 1
URL      : https://github.com/openstack/stx-fault/archive//80afa6133f70b6e3e25befe3f993c2a1bf1cb0bf.tar.gz
Source0  : https://github.com/openstack/stx-fault/archive//80afa6133f70b6e3e25befe3f993c2a1bf1cb0bf.tar.gz
Summary  : CGTS Platform SNMP extension Package
Group    : Development/Tools
License  : Apache-2.0
Requires: fm-mgr-config
BuildRequires : buildreq-distutils3
BuildRequires : fm-common-dev
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : systemd-devel
BuildRequires : tox
BuildRequires : util-linux-dev
BuildRequires : virtualenv

%description
Titanium Cloud platform Fault Management Client Library that provides APIs for
applications to raise/clear/update active alarms.

%package config
Summary: config components for the fm-mgr package.
Group: Default

%description config
config components for the fm-mgr package.


%prep
%setup -q -n stx-fault-80afa6133f70b6e3e25befe3f993c2a1bf1cb0bf

%build
## build_prepend content
version=%{version}
MAJOR=${version%%.*}
MINOR=${version##*.}
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538978305
pushd fm-mgr/sources
make  %{?_smp_mflags} MAJOR=${version%%.*} MINOR=${version##*.} EXTRACCFLAGS="$CXXFLAGS"
popd

%install
export SOURCE_DATE_EPOCH=1538978305
rm -rf %{buildroot}
pushd fm-mgr/sources
echo "Empty"
popd
## install_append content
pushd fm-mgr/sources
version=%{version}
make DEST_DIR=%{buildroot} MAJOR=${version%%.*} MINOR=${version##*.} install_non_bb
%global _sysconfdir '/usr/local/etc'
install -d %{buildroot}/usr/lib/systemd/system
install -m 755 -d %{buildroot}/%{_sysconfdir}
install -m 755 -d %{buildroot}/%{_sysconfdir}/init.d
install -m 755 -d %{buildroot}/%{_sysconfdir}/logrotate.d
install -m 755 fminit %{buildroot}/%{_sysconfdir}/init.d/fminit
install -m 755 fmManager %{buildroot}/usr/local/bin/fmManager
install -m 644 fm.logrotate %{buildroot}/%{_sysconfdir}/logrotate.d/fm.logrotate
install -m 644 fminit.service %{buildroot}/usr/lib/systemd/system/fminit.service
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/bin/fmManager
/usr/local/etc/init.d/fminit
/usr/local/etc/logrotate.d/fm.logrotate

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/fminit.service
